language: go
go:
    - 1.13.4

# script:
#     - env GO111MODULE=on go build
#     - env GO111MODULE=on go test

services:
    - docker

before_install:
    - ls
    - cp -r !(Docker) Docker/
    - cd Docker; docker-compose -f travis-docker-compose.yml run --entrypoint="go test" test-web-backend