language: go
go:
    - 1.13.4

script:
    - env GO111MODULE=on go build
    - env GO111MODULE=on go test

services:
    - docker
before_install:
    - go build -o Docker/
    - cd Docker; docker-compose run --entrypoint="go test" docker_web-backend