language: go
services:
    - docker
before_install:
    - docker-compose build -f Docker/docker-compose.yml
    - cd Docker; docker-compose up
    - docker exec -it $(docker ps | grep docker_dev-web-backend_1 | awk '{print $1}'); cd tests; go test"