language: go
go:
    - 1.13.4

# script:
#     - env GO111MODULE=on go build
#     - env GO111MODULE=on go test

services:
    - docker

before_install:
    - ls
    - mkdir Docker/code
    - cp -r !(Docker) Docker/code/
    - cd Docker
    - ls
    - rm -rf docker-compose.yml
    - mv travis-docker-compose.yml docker-compose.yml