version: '3.4'
services:
  redis:
    image: "redis:6.0.6"
  postgres:
    build:
      context: .
      dockerfile: postgresql.dockerfile

  test-web-backend:
    depends_on: 
      - postgres
      - redis
    
    working_dir: /code/tests
    
    build:
      context: .
      dockerfile: test-web-backend.dockerfile