version: '3.4'
services:
  redis:
    image: "redis:6.0.6"
  postgres:
    build:
      context: .
      dockerfile: postgresql.dockerfile

  web-backend:
    build: 
      context: .
      dockerfile: backend.dockerfile

    depends_on: 
      - redis
      - postgres

    ports:
      - "8000:8000"

    # tty: true

  test-web-backend:
    depends_on: 
      - postgres
      - redis
    
    build:
      context: .
      dockerfile: dev-backend.dockerfile

  dev-web-backend:
    depends_on: 
      - postgres
      - redis
    build:
      context: .
      dockerfile: dev-backend.dockerfile
  
    volumes:
      - ../:/app

    working_dir: /app
  
    ports:
      - "8001:8000"

volumes:
  code-files:
      external: false