swagger: "2.0"
info:
  title: Cases
  description: API to make CRUD operations for the cases
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/cases/add:
    post:
      tags:
      - cases
      summary: add cases
      operationId: cases#add
      parameters:
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/CasesAddRequestBody'
          required:
          - desc
          - target
          - collected
          - currency
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CasesAddResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/CasesAddUnauthorizedResponseBody'
      schemes:
      - http
  /api/cases/get:
    get:
      tags:
      - cases
      summary: get cases
      operationId: cases#get
      parameters:
      - name: GetRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/CasesGetRequestBody'
          required:
          - token
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/GetResponseResponse'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/CasesGetUnauthorizedResponseBody'
        "403":
          description: Forbidden response.
          schema:
            $ref: '#/definitions/CasesGetInvalidScopesResponseBody'
      schemes:
      - http
definitions:
  CasesAddRequestBody:
    title: CasesAddRequestBody
    type: object
    properties:
      collected:
        type: number
        description: Collected Quantity
        example: 0.49711351694702943
        format: double
      currency:
        type: string
        description: Currency
        example: Esse debitis ut incidunt error quam provident.
      desc:
        type: string
        description: Case Description
        example: Porro et deserunt.
      tags:
        type: array
        items:
          type: string
          example: Odio ratione.
        description: Tags array
        example:
        - Ipsa aut incidunt.
        - Vel ducimus accusamus porro.
        - Aut ducimus quasi non ad.
      target:
        type: number
        description: Target Quantity
        example: 0.35476548967530164
        format: double
    example:
      collected: 0.38202232630928523
      currency: Temporibus accusamus.
      desc: Odit et accusamus.
      tags:
      - Ut veniam quas deserunt.
      - Ut deleniti.
      - Voluptate et assumenda ut quo est explicabo.
      target: 0.7461176962398828
    required:
    - desc
    - target
    - collected
    - currency
  CasesAddResponseBody:
    title: CasesAddResponseBody
    type: object
    properties:
      desc:
        type: string
        description: The description of the case
        example: Fugit adipisci et.
    example:
      desc: Cupiditate soluta modi nihil.
  CasesAddUnauthorizedResponseBody:
    title: CasesAddUnauthorizedResponseBody
    type: string
    description: Credentials are invalid
    example: Quis aut.
  CasesGetInvalidScopesResponseBody:
    title: CasesGetInvalidScopesResponseBody
    type: string
    description: Token scopes are invalid
    example: Facere et vel et enim.
  CasesGetRequestBody:
    title: CasesGetRequestBody
    type: object
    properties:
      token:
        type: string
        description: JWT used for authentication
        example: Perspiciatis ad aperiam qui provident.
    example:
      token: Officia laudantium repellat porro voluptatibus odio ipsa.
    required:
    - token
  CasesGetUnauthorizedResponseBody:
    title: CasesGetUnauthorizedResponseBody
    type: string
    description: Credentials are invalid
    example: Voluptas a.
  GetResponseResponse:
    title: GetResponseResponse
    type: object
    properties:
      Collected:
        type: number
        description: Collected value
        example: 0.17048738161674107
        format: double
      Currency:
        type: string
        description: Currency
        example: Maxime dolores optio ut.
      DateModified:
        type: string
        description: Date Modified in the database
        example: Numquam ea architecto laborum aut omnis.
      Description:
        type: string
        description: Case Description
        example: Nostrum qui similique neque debitis dolor.
      ID:
        type: integer
        description: Case ID
        example: 7489333034111920853
        format: int64
      Tags:
        type: array
        items:
          type: string
          example: Saepe nobis aut qui consequatur.
        description: Tags
        example:
        - Labore quia perspiciatis omnis.
        - Illo id.
      Target:
        type: number
        description: Targetted value
        example: 0.7207897685346668
        format: double
    example:
      Collected: 0.540506236496741
      Currency: Qui laudantium eum eaque.
      DateModified: Perferendis sapiente et similique.
      Description: Voluptate ut itaque non ipsum facilis sunt.
      ID: 9579606506905698090
      Tags:
      - Placeat dolores saepe voluptatum molestiae cum.
      - Eligendi reprehenderit culpa id quas.
      Target: 0.13127594859952696
